[config]
default_to_workspace = false

[env]
CARGO_MAKE_COVERAGE_PROVIDER = "tarpaulin"

[tasks.build]
command = "cargo"
args = ["build", "--examples"]

[tasks.rebuild]
dependencies = ["clean", "build"]

[tasks.run]
command = "cargo"
args = ["run", "--example", "demo"]

[tasks.test]
command = "cargo"
args = ["test", "--workspace"]

[tasks.test-ci]
script_runner = "pwsh"
script_extension = "ps1"
script = """
cd crates\\aleph-app && cargo test && cd ..\\..
cd crates\\aleph-core && cargo test && cd ..\\..
cd crates\\aleph-scene && cargo test && cd ..\\..
cd crates\\aleph-gfx && cargo test && cd ..\\..
cd crates\\aleph-vk && cargo test && cd ..\\..
"""

[tasks.coverage]
command = "cargo"
args = ["tarpaulin", "--ignore-tests", "--workspace", "--all-targets"]

[tasks.clean]
dependencies = ["clean-rs", "clean-shaders"]

[tasks.clean-rs]
script_runner = "pwsh"
script_extension = "ps1"
script = """
pwsh.exe -C "Remove-Item -Path target -Forc -Recurse -ErrorAction Ignore"
"""

[tasks.clean-shaders]
script_runner = "pwsh"
script_extension = "ps1"
script = """
pwsh.exe -C "Remove-Item -Path shaders/*.spv -Force -ErrorAction Ignore"
"""

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.fix]
command = "cargo"
args = ["fix", "--workspace",    "--allow-dirty", "--allow-staged"]

[tasks.log]
script_runner = "@shell"
script = """
cargo run --example demo *> log.txt
"""
